language: java
jdk:
- oraclejdk8
dist: trusty
cache:
  directories:
  - "$HOME/.m2"
before_install:
- export PATH=$PATH:${TRAVIS_BUILD_DIR}/target
install:
- sudo apt-get install -y gnupg2
script:
- "./mvnw install -Dmaven.javadoc.skip=true -B -V -e"
after_success:
- if [[ "$(echo 'VERSION=${project.version}' | ./mvnw org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate
  | grep '^VERSION')" == *-SNAPSHOT ]]; then export IS_SNAPSHOT=true; fi
deploy:
- provider: script
  script: ".travis/publish.sh"
  skip_cleanup: true
  on:
    repo: cerner/beadledom
    branch: master
    condition: "${IS_SNAPSHOT} = true"
- provider: script
  script: ".travis/publish.sh"
  skip_cleanup: true
  on:
    repo: cerner/beadledom
    tags: true
branches:
  only:
  - master
  - beta
  - "/([0-9]*\\.[0-9]*\\.*[0-9]*-*)\\w+$/"
env:
  global:
  - CI_DIR=${TRAVIS_BUILD_DIR}/.travis
  - secure: dt/hn9uxAC2A89ANiRYum7oHsFWpR1PmSudXvfbneHmnfaVcs8jAUJOYL0wpqolMR4lN/D6mWjHm/7vktsE7axFrtq8izHyC9Hh3M6r7GW+FD/amhrav4pz0z6YzGnNt0dQpdlBEs7viY8eBl8hUCKbkeyXy8ocnS5meh7Oh025ayD2EAvSS8aLl7WdrCL8lbb8uzFSQTUTWCr13YKFouIy6vKBjDgsjBmjyCIa5WsUIlRfi/r/zUIkpjxoY1mg4Am8J8TsH4Fu94BuH8YnA/yRg8nqHfyL22bTTLLAYpT3AhtSQCE5Df4XDC5cQKy4lTEWQNX3ypVdFzi8UDx74Uin0OEc2H1pxK1uZiNAVgHC0yuUKJHS/XN8bTQGDrXjPri9DmrPXkb2sXSrpv00xE5ZEFhDR2ZurqRpoAvRjGk3fxBvzWdcCb+DHbVRoVclCyTqkc8r9u1q2Woed1CtG24plaCjkzJIg/uZzB1fJfSHMDtkv5GBH85yDyyi3t+04m8Gxhu/A0Ej9cLz9tnqogoxM+Se/PeemJ/I085G7FH7OhlWZZXmeJ4CpjVPyYpxSUdZZ0hB+UjI7hcP7pyCnUe9XHrvIUab7UdjRinq1H0eGmPjWaHEYq9EOP/vqHuQrEFX87c4bPnpr4A5Tq5TCPxvNgIjyZ1DW0lm9Tcsc/dI=
  - secure: BVyKlQ6mBxfq2gWHoTh0sZDYBFOXZu3HCaexmisNMXkvzjtDaLF6EUhJmGkYxz8aH4mT2xF0KMSlABI+HWevPCyktailvjAtfFtKuPgmMixbHHKxweuML2Z1qlQYm1+U0USnYu/RB6mxtxyNhACSO+HaVLE8TQfc/2L+gQVGtOuxCWBzKiNHWA5nDXVTF4TxVqwmyg9X0Y4ZGgdBEqMCCoBju1xORPIUTs0CTMzJJEZSw4FCLwCpw4xJ3kc7CRqooIrc99AhPg7Kw+9GVfLwe+ZPKcx7r8YYUNaVjnV1C8LJrsD4rTuZuj4ILNViI6foidUiwNURCUwodX7Q8new4KTyEPILuKBVlY2b+bJPTNCRa3qiXcgMNDfUWx9Zcl4VIRB3QH0nV97E+z52UcDqZihtQPsJhfws6YnF9AHz1h7hsizo3a5asCMtLaENat4FAxP56o9I0MWGK8zvoao9c1V5GH1GgHqT8i19EB3MNbk0NQfe4Bps1AFcgK/CgCGH6UYDIUfEb4uR+CsKCDD77zcC99ByUmBq22f4LiPykWomX1A/b37LQF2ci8AkrJ4rv2n8uaHK/T8EfkghixSlXNc3HOysauC7Wr0beB4xfgB1o0hecMezbqaHJxnRu8f/IKeowP5l+f4KZIKILKb83V+b1dh8jZhDg3xMKkVvKUY=
  - secure: sJcpQrh3XV+yftV9YHiws8O74jjVb1Lrem5vFqUI/wHtSmzBHcSQhANFjxBCfvKGG5TqkMXGFLdWiUoygbbzVT+M60MS9vvrNcuojFFxfWZZcrDtxOnFZM39vUl4PPMeo+YBcNm1E2DAPo3i1ls1DOO7VS/qZ8CGpjzpggBIqC8ib2Obo+SKxqrRkScziXBVkBhNSKiAg4fcNU+aobH4JJ1eZfrs3eitQAI1sDvD0gDOd5ZxRbDu5XdebaWvsf9ZjlUU4KRLMIxAvbfORnkWGzGhthiGKpv2z9N7pUK7/VErrOisYGWFq8Ff0VfAFZagr4CF0WLbrMnLTU1W3ymbhyyU0QLboD8+rDaUjTpZu/zc9V7mg7lZjA7oLLNW5E50XiF4KpMcKoliyhx+XJsV4XFdLJbQfpN+XeVObicPVgZhjj4jiO6d2WouijOzi6zxDHjVSbuHnk2IrS8oWaJOJRY2BSsBB8EF8Ymzon4QNfOaS2d/7J1w/HQxO8tguRXBkqVNpKuCusi7kfwysvvHTHhyOM/n4ISaLP6HzBnPriyvjKEKU9XyOvfIHNhWULXotHCz3YazYL3iU1soyoETViRSp2Mw9b1skmCI5dE9nQIjUo1XXhJGESrD/rZ9T+04ry1QxcBAmlZxxYXsuDPJjkQGlZZq1KFsj8w8TSD4EEA=
  - secure: wez7cLEe0/Xv5WrePj+uoANjBlnSjPFs1AHONXCUKRwQFv9Kdj5fVUIK3Msu7Whbm7Moqb6CewGlJE84tvcOMrXCpQscQtdSvB4AZEbdcRvRs+icM+/F0LZLA5Igzrg7ayjCa/cvkcAERbrgpGuMY4/RFvDD5TW1/7Ytd9bfL3rRxi81Pg0M2YzbnBtpC1fhDq6BUsP2kkcoRySjnWjwvXVxabgXiCcuKQI4qAmI/SCeJYMMNnXjbaERxIi9lCt9kKxvhTi8T/HA6uUFU7Sjyackfe7BYkPJE/6gfyp4VJQzNdoG7OnVATHqf+sOPRoYiJrOCgLXT5aes18UyoA+lRAG2MWJYrWIWUXDJQi61RDlzKsjWKsfd27XTN55X1dqRMpZti/DN9euSd7bU443btYEB7IR6wRsmc4fiR0KtDK4vsL9pFu8czJDGR3vt9H3zMgR8zbIJjgPiXjywjPr7Y7pOD21OjLrka/6dO0vYtWdfPY5Y6tzU1du7HF4B07Ouir54s//ce+8NKXIagfBwF77aoG+KfZePrMqT7rwBtv1yGucOOhbwT22fu5YNXiD1IXndSaLhOQtL6LQsK12btbHS/8AzuJrZFZv7UrD1C0t39y8ForKgOYELAOQplnD312LdzUW+d8JALohKPZhqnOAJ8s+g21dl9AgJt7fA5k=
  - secure: nFImXEZsNsNfhxM233gfK2gEhwS5lpJQXC3DYsS8sLVipbhM/B9qksmg6gu/fzZ4vEzO6JIMf86hZYmKzIqHnrglf4RA9FnG4FM1J3//KcLs5lRFTV/rT+k+YJDRsdhrCYyVYR6JxJl8sCbLAkK5x8nMnGE0Q1KLo4vER9TO0RRe/ETTGIGpWQgTW7Q2sSagsYqvSpYnZ3LgTl6AOq3tFnvo3gVKJRNZ9u9gexOdc3BVrZ+oBtZIApj+LgZzdbHVmkDSMwJyWEJYbaoimQ72k1N5MUHKJJ7O6xJyoB1JPu+dNPcyT+wQveXQNj+5ZKo05PesRKHSpcCfc72KtWvCyW6TVz2BUXt3b5koMo5du6vsDzZltAQ3bxm0hd8uvsMa+pyAbBM2jEK7E/DqfKESt0Os+QT8JdJ6W2uLM3EqRv1xbpb1W3eRck97LsB5Bj/ED511Fjj3Eb8IgOissUf1hQZwh/3DwMJ6VB+UxpmUq/QfoNksvibhTXmslCCg/HRUhhkRY9dnhC6zEiS9zG9QTYZX60TsbREAsr+TY78KXFQrekLHtiEhvBNQkFjGsTQMvPWc3F3FvqwOCYCcEYtEb/Xjw1e4W7mf6ZSXks2jDW6pql75Lt4bScJZs+yZLGysoiRORhM1s2y7+KJXgQba7nppZDldZ2oNQIU2zaKDDC4=
  - secure: QW7LTdri+aX6hDyk7IgSnQy90mLTt0eAjcNZUEzSEjbickBYTjzfN6vg+CbgIQCTSwDqGk/E/2e7FL50XVzs0nL1wcpw1kX3pQyW5vfXxGGvgvjpAYZPJK54ur0kv2QOjfPrRhkuKjBZtHpbGfSRHG0VrFA4kVeObtUK3QulpJgWjpmsF6qQo9D+pWDokgIt0gyq1UOlDs6MQih0uchF1XimuNSsH6Y5x0RwNrB1WkaiT6lwwT9Vn3djyMMSa1bkFhEYAMwRrgjJMvq/yGyh/TdLqCFK9Uo0YKvrUm+ydxPFLsorfERTbg7WuNHDmTsAoPbAu9Y8jHnRSa2lj6+MiJbwb/EmgQ6KZXEGu1X7dqJxYO0W2dX1CBHcNh7wvk20GU/qcHV0pAzrBjsENxr7g3D8q5tbBccJSgHWcOT05O8B1J/J4PkvOLn8cA+NYTxUvIi3/qFHQVJWQkkZCwgVlt+SBmAQCr7BVEUpY/upWEjDjbYOFr5Ro9w/gjXh+e6YDpkQjkF8TbbQxpa3n+MsJ6tW675Byty4RX1OVAcsKha0sfEaq03+QJ8+ErSmQqfvIkB5K05lm236rZQG9yFMpaMvZQw5E5U3HQ4ioZ0mHmLsA7Yxc2BMK14/rw+umvtCV7vD/hyFkk/5MxxF/Z1HTDQS3IS1ggFfo6jnj4R37aY=
